import { CreateEventFom } from "components/form";
import Head from "next/head";

const CreateEvent = () => {
	return (
		<>
			<Head>
				<title>Create Event - RSVP</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="layout-container">
				<div className="flex flex-col items-center pt-20 text-white max-w-lg mx-auto">
					<h1 className="text-3xl font-bold">Create a new Event</h1>
					<p className="text-gray-400 text-xl">it is quick and easy</p>
					<CreateEventFom />
				</div>
			</div>
		</>
	);
};

export default CreateEvent;
